/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import ca.hdsb.gwss.ahmad.ics3u.u6.*;
import java.text.NumberFormat;

/**
 *
 * @author 1elmasriahm
 */
public class Temperature extends javax.swing.JFrame {

    /**
     * Creates new form GoldScore
     */
    int[] x = new int[7];
    String s = "";
    int holder;
    int studentCount = 0;

    public Temperature() {
        initComponents();
        jButtonDisplayScore.setEnabled(false);
        jLabelGolfScore.setText("Hole " + (studentCount + 1) + ": ");
        jLabelHighestNumber.setText("");
        jLabelLowestNumber.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIntro = new javax.swing.JTextArea();
        jTextFieldScore = new javax.swing.JTextField();
        jLabelGolfScore = new javax.swing.JLabel();
        jButtonAddScore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonDisplayScore = new javax.swing.JButton();
        jLabelMaximumScore = new javax.swing.JLabel();
        jLabelHighestNumber = new javax.swing.JLabel();
        jLabelMinimumScore = new javax.swing.JLabel();
        jLabelLowestNumber = new javax.swing.JLabel();
        jLabelAverage = new javax.swing.JLabel();
        jLabelNumberinBetween = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ics3u.Golf Score");

        jPanelHeader.setBackground(new java.awt.Color(153, 255, 153));
        jPanelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 10));
        jPanelHeader.setForeground(new java.awt.Color(0, 102, 0));
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseClicked(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitle.setText("ICS3U - Golf Score");

        jTextAreaIntro.setColumns(20);
        jTextAreaIntro.setLineWrap(true);
        jTextAreaIntro.setRows(5);
        jScrollPane1.setViewportView(jTextAreaIntro);

        jTextFieldScore.setText("Add Score");
        jTextFieldScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldScoreMouseClicked(evt);
            }
        });
        jTextFieldScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldScoreActionPerformed(evt);
            }
        });

        jLabelGolfScore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGolfScore.setText("Score: ");

        jButtonAddScore.setText("Add Score");
        jButtonAddScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddScoreMouseClicked(evt);
            }
        });
        jButtonAddScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddScoreActionPerformed(evt);
            }
        });

        jLabel2.setText("Score List:");

        jButtonDisplayScore.setText("Display Score");
        jButtonDisplayScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisplayScoreActionPerformed(evt);
            }
        });

        jLabelMaximumScore.setText("Maximum Score : ");

        jLabelHighestNumber.setText("jLabel4");

        jLabelMinimumScore.setText("Minimum Score : ");

        jLabelLowestNumber.setText("jLabel4");

        jLabelAverage.setText("Average : ");

        jLabelNumberinBetween.setText("jLabel4");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelTitle))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabelGolfScore)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddScore))
                    .addComponent(jLabel2)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDisplayScore)
                        .addGap(68, 68, 68)
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                                .addComponent(jLabelMaximumScore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelHighestNumber))
                            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                                    .addComponent(jLabelAverage)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNumberinBetween))
                                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                                    .addComponent(jLabelMinimumScore)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelLowestNumber))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGolfScore)
                    .addComponent(jButtonAddScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDisplayScore)
                            .addComponent(jLabelMaximumScore)
                            .addComponent(jLabelHighestNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMinimumScore)
                            .addComponent(jLabelLowestNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAverage)
                            .addComponent(jLabelNumberinBetween))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddScoreActionPerformed

    private void jTextFieldScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldScoreActionPerformed

    private void jTextFieldScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldScoreMouseClicked
        jTextFieldScore.setText("");
    }//GEN-LAST:event_jTextFieldScoreMouseClicked

    private void jButtonAddScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddScoreMouseClicked
        try {
            
            holder = Integer.parseInt(jTextFieldScore.getText());
            if(holder >= 1){
            x[studentCount] = holder;
            s += "Hole " + (studentCount + 1) + ": " + x[studentCount] + "\n";
            jTextFieldScore.setText("Add Score");
            jLabelGolfScore.setText("Hole " + (studentCount + 2) + ": ");
            studentCount++;
            }else{
                jTextFieldScore.setText("Invalid Input, try again");
            }
        } catch (Exception e) {

            jTextFieldScore.setText("Invalid input, try again");
        }
            
        if (studentCount >= 18) {
            NumberFormat decimal = NumberFormat.getNumberInstance(); 
            decimal.setMinimumFractionDigits( 3 );
            decimal.setMaximumFractionDigits( 3 );
            jButtonDisplayScore.setEnabled(true);
            jButtonAddScore.setEnabled(false);
            jLabelGolfScore.setText("Done");
            jLabelHighestNumber.setText("" + ArrayUtil.max(x));
            jLabelLowestNumber.setText("" + ArrayUtil.min(x));
            jLabelNumberinBetween.setText("" + decimal.format(ArrayUtil.average(x)));

        }
    }//GEN-LAST:event_jButtonAddScoreMouseClicked

    private void jButtonDisplayScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisplayScoreActionPerformed
        // TODO add your handling code here:
        jTextAreaIntro.setText(s);
    }//GEN-LAST:event_jButtonDisplayScoreActionPerformed

    private void jPanelHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseClicked
        jTextFieldScore.setText("Add Score");
    }//GEN-LAST:event_jPanelHeaderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperature().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddScore;
    private javax.swing.JButton jButtonDisplayScore;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAverage;
    private javax.swing.JLabel jLabelGolfScore;
    private javax.swing.JLabel jLabelHighestNumber;
    private javax.swing.JLabel jLabelLowestNumber;
    private javax.swing.JLabel jLabelMaximumScore;
    private javax.swing.JLabel jLabelMinimumScore;
    private javax.swing.JLabel jLabelNumberinBetween;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaIntro;
    private javax.swing.JTextField jTextFieldScore;
    // End of variables declaration//GEN-END:variables
}
